changing ci file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,8 +23,8 @@ jobs:
     - name: Install dependencies
       run: npm ci
 
-    - name: Run tests
-      run: npm test  # Remove '|| true' if you want failures to stop the workflow
+    # - name: Run tests
+    #   run: npm test  # Remove '|| true' if you want failures to stop the workflow
 
 
     - name: Build application (optional)
